server:
  port: 8771
#zipkin服务所在地址
  zipkin:
    base-url: http://192.168.3.222:9411/
#配置采样百分比 开发环境可以设置为1=100%
  sleuth:
    sampler:
      probability: 1
env: 多节点测试
branch: master
#rabbitmq消息中间件
  rabbitmq:
    host: 192.168.3.222
    port: 5671
    username: guest
    password: guest
      #读取哪个分支
      label: master
#actuator监控追踪 *代表打印全部
management:
    endpoints:
      web:
        exposure:
          include: "*"
